-- SELECT QUERIES
SELECT ID, NAME, COURSE FROM STUDENT;
SELECT NAME, COURSE, ID FROM STUDENT;

-- WHERE CLAUSE
SELECT * FROM STUDENT WHERE COURSE = 'JAVA';
SELECT * FROM STUDENT WHERE COURSE = 'JAVA' AND CITY = 'PUNE';
SELECT * FROM STUDENT WHERE COURSE = 'PYTHON' OR CITY = 'MUMBAI';
SELECT * FROM STUDENT WHERE NAME = 'YASH';

-- COMPARISON OPERATORS
SELECT * FROM STUDENT WHERE ID % 2 != 0;
SELECT * FROM STUDENT WHERE ID % 2 = 0;
SELECT * FROM STUDENT WHERE AGE >= 20 AND AGE <= 23;
SELECT * FROM STUDENT WHERE AGE <> 23;

-- BETWEEN OPERATOR
SELECT * FROM STUDENT WHERE AGE BETWEEN 20 AND 23;
SELECT * FROM STUDENT WHERE AGE NOT BETWEEN 20 AND 23;

-- IN OPERATOR
SELECT * FROM STUDENT WHERE AGE IN (20, 25);
SELECT * FROM STUDENT WHERE AGE NOT IN (20, 25);
SELECT * FROM STUDENT WHERE CITY IN ('PUNE', 'MUMBAI');
SELECT * FROM STUDENT WHERE CITY NOT IN ('PUNE', 'MUMBAI');

-- LIKE OPERATOR
SELECT * FROM STUDENT WHERE NAME LIKE 'K%';
SELECT * FROM STUDENT WHERE CITY LIKE '%PUR';
SELECT * FROM STUDENT WHERE NAME LIKE '__O%';
SELECT * FROM STUDENT WHERE NAME LIKE '%K%A%';
SELECT * FROM STUDENT WHERE NAME LIKE '%OO%';